# Generated by Django 3.1.2 on 2021-12-06 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='icon/', verbose_name='アイコン')),
                ('name', models.CharField(max_length=20, verbose_name='アイコンの名前')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=2000, verbose_name='コメント')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='緯度')),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='経度')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.icon', verbose_name='アイコン')),
            ],
        ),
    ]
